// <auto-generated />
using Beca.ConciertoInfo.API.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Beca.ConciertoInfo.API.Migrations
{
    [DbContext(typeof(ConciertoInfoContext))]
    partial class ConciertoInfoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("Beca.ConciertoInfo.API.Entities.Concierto", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("Description")
                    .HasMaxLength(300)
                    .HasColumnType("TEXT");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.ToTable("Albumes");

                b.HasData(
                    new
                    {
                        Id = 1,
                        Description = "Concierto de Izal.",
                        Title = "Izal"
                    },
                    new
                    {
                        Id = 2,
                        Description = "Concierto de Imagine Dragons.",
                        Title = "Imagine Dragons"
                    },
                    new
                    {
                        Id = 3,
                        Description = "Concierto de OneRepublic.",
                        Title = "OneRepublic"
                    });
            });

            modelBuilder.Entity("Beca.ConciertoInfo.API.Entities.Cancion", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<int>("ConciertoId")
                    .HasColumnType("INTEGER");

                b.Property<string>("Description")
                    .HasMaxLength(300)
                    .HasColumnType("TEXT");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("ConciertoId");

                b.ToTable("Canciones");

                b.HasData(
                    new
                    {
                        Id = 1,
                        AlbumId = 1,
                        Description = "Incluso ahora\r\nQue ya no hay miedo\r\nQue nada tiembla\r\nSal de baño\r\nBrillo dorado en la piel",
                        Title = "Copacabana"
                    },
                    new
                    {
                        Id = 2,
                        AlbumId = 1,
                        Description = "Bailando hasta que todo acabe\r\nYa no importa lo que digan y menos lo que callen\r\nQue nos miren, que sientan, que rían, que se unan al baile\r\nBienvenidos a la última fiesta del no somos nadie",
                        Title = "El baile"
                    },
                    new
                    {
                        Id = 3,
                        AlbumId = 2,
                        Description = "Sometimes I wish that I could wish it all away\r\nOne more rainy day without you\r\nSometimes I wish that I could see you one more day\r\nOne more rainy day",
                        Title = "Wrecked"
                    },
                    new
                    {
                        Id = 4,
                        AlbumId = 2,
                        Description = "We're walking the wire, love\r\nWe're walking the wire, love\r\nWe couldn't be higher, up\r\nWe're walking the wire, wire, wire",
                        Title = "Walking The Wire"
                    },
                    new
                    {
                        Id = 5,
                        AlbumId = 3,
                        Description = "You're gonna grow up, you're gonna get old\r\nAll that glitter don't turn to gold\r\nBut until then, just have your fun\r\nBoy, run, run, run, run, run",
                        Title = "Run"
                    },
                    new
                    {
                        Id = 6,
                        AlbumId = 3,
                        Description = "Oh, I know that there'll be better days\r\nOh, that sunshine 'bout to come my way\r\nMay we never ever shed another tear for today\r\n'Cause, oh, I know that there'll be better days",
                        Title = "Better Days"
                    });
            });

            modelBuilder.Entity("Beca.ConciertoInfo.API.Entities.Cancion", b =>
            {
                b.HasOne("Beca.ConciertoInfo.API.Entities.Concierto", "Concierto")
                    .WithMany("Canciones")
                    .HasForeignKey("ConciertoId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Concierto");
            });

            modelBuilder.Entity("Beca.ConciertoInfo.API.Entities.Concierto", b =>
            {
                b.Navigation("Canciones");
            });
#pragma warning restore 612, 618
        }
    }
}
